-- [nfnl] Compiled from fnl/keymaps.fnl by https://github.com/Olical/nfnl, do not edit.
local _local_1_ = require("nfnl.module")
local autoload = _local_1_["autoload"]
local builtin = autoload("telescope.builtin")
local function map_opt(mode, shortcut, command, opt)
  _G.assert((nil ~= opt), "Missing argument opt on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:4")
  _G.assert((nil ~= command), "Missing argument command on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:4")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:4")
  _G.assert((nil ~= mode), "Missing argument mode on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:4")
  return vim.keymap.set(mode, shortcut, command, opt)
end
local function map(mode, shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:7")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:7")
  _G.assert((nil ~= mode), "Missing argument mode on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:7")
  return vim.keymap.set(mode, shortcut, command, {noremap = true, silent = true})
end
local function nmap(shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:10")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:10")
  return map("n", shortcut, command)
end
local function imap(shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:13")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:13")
  return map("i", shortcut, command)
end
local function tmap(shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:16")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /Users/trollham/dotfiles/nvim/fnl/keymaps.fnl:16")
  return map("t", shortcut, command)
end
imap("jk", "<Esc>")
tmap("jk", "<C-\\><C-n>")
tmap("<M-h>", "<C-\\><C-N><C-w>h")
tmap("<M-j>", "<C-\\><C-N><C-w>j")
tmap("<M-k>", "<C-\\><C-N><C-w>k")
tmap("<M-l>", "<C-\\><C-N><C-w>l")
imap("<M-h>", "<C-\\><C-N><C-w>h")
imap("<M-j>", "<C-\\><C-N><C-w>j")
imap("<M-k>", "<C-\\><C-N><C-w>k")
imap("<M-l>", "<C-\\><C-N><C-w>l")
nmap("<M-h>", "<C-w>h")
nmap("<M-j>", "<C-w>j")
nmap("<M-k>", "<C-w>k")
nmap("<M-l>", "<C-w>l")
map_opt("n", "<leader>g", builtin.live_grep, {})
map_opt("n", "<leader>f", builtin.find_files, {})
map_opt("n", "<leader>b", builtin.buffers, {})
return {}
