-- [nfnl] fnl/keymaps.fnl
local function map(mode, shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /home/ehuff/.config/nvim/fnl/keymaps.fnl:1")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /home/ehuff/.config/nvim/fnl/keymaps.fnl:1")
  _G.assert((nil ~= mode), "Missing argument mode on /home/ehuff/.config/nvim/fnl/keymaps.fnl:1")
  return vim.keymap.set(mode, shortcut, command, {noremap = true, silent = true})
end
local function nmap(shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /home/ehuff/.config/nvim/fnl/keymaps.fnl:4")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /home/ehuff/.config/nvim/fnl/keymaps.fnl:4")
  return map("n", shortcut, command)
end
local function imap(shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /home/ehuff/.config/nvim/fnl/keymaps.fnl:7")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /home/ehuff/.config/nvim/fnl/keymaps.fnl:7")
  return map("i", shortcut, command)
end
local function tmap(shortcut, command)
  _G.assert((nil ~= command), "Missing argument command on /home/ehuff/.config/nvim/fnl/keymaps.fnl:10")
  _G.assert((nil ~= shortcut), "Missing argument shortcut on /home/ehuff/.config/nvim/fnl/keymaps.fnl:10")
  return map("t", shortcut, command)
end
imap("jk", "<Esc>")
tmap("jk", "<C-\\><C-n>")
tmap("<M-h>", "<C-\\><C-N><C-w>h")
tmap("<M-j>", "<C-\\><C-N><C-w>j")
tmap("<M-k>", "<C-\\><C-N><C-w>k")
tmap("<M-l>", "<C-\\><C-N><C-w>l")
imap("<M-h>", "<C-\\><C-N><C-w>h")
imap("<M-j>", "<C-\\><C-N><C-w>j")
imap("<M-k>", "<C-\\><C-N><C-w>k")
imap("<M-l>", "<C-\\><C-N><C-w>l")
nmap("<M-h>", "<C-w>h")
nmap("<M-j>", "<C-w>j")
nmap("<M-k>", "<C-w>k")
nmap("<M-l>", "<C-w>l")
return {}
